version: "3.5"

services:
    web:
        image: nginx
        container_name: ecommerce_webui
        volumes:
            - ./nginx_test.conf.template:/etc/nginx/conf.d/nginx_test.conf.template
            - ./UIService:/usr/share/nginx/html
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
            - CUSTOMER_DOMAIN=localhost
            - CUSTOMER_PORT=4000
            - QUESTION_DOMAIN=localhost
            - QUESTION_PORT=4001
            - QUALITY_DOMAIN=localhost
            - QUALITY_PORT=4002
        command: /bin/bash -c
            "envsubst
            < /etc/nginx/conf.d/nginx_test.conf.template
            > /etc/nginx/conf.d/nginx_test.conf
            && exec nginx -c /etc/nginx/conf.d/nginx_test.conf -g 'daemon off;'"