version: "3.5"

services:
    mysql-service-questions:
        image: mysql:5
        container_name: mysql-service-questions
        # Uncomment to save data on local file system
        # volumes:
        #   - database_vol:/var/lib/mysql/data

        environment:
            MYSQL_USER: springuser
            MYSQL_PASSWORD: springpassword
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: question_service_db
        healthcheck:
            test: ["CMD-SHELL", 'mysqladmin status --password=example']
            interval: 10s
            timeout: 2s
            retries: 10
        networks:
          - local

    question-service:
        image: aceofwands/question_generator_service:0.1
        # Local Image
        # image: customer_service_example
        container_name: question-service
        restart: on-failure
        ports:
            #- 8081:8080
            - 4001:4000
        environment:   
            WAIT_HOSTS: mysql-service-questions:3306
            db_host: mysql-service-questions
            db_username: springuser
            db_pass: springpassword
            db_database: question_service_db
            db_port: 3306
            server_port: 4000
            quests_file: ./questions.json
        links:
            - mysql-service-questions
        depends_on:
            - mysql-service-questions
        volumes:
            - ./questions.json:/home/app/questions.json
        networks:
          - local
          - outside

    # phpmyadmin:
        # image: phpmyadmin/phpmyadmin
        # restart: always
        # environment: 
            # PMA_HOST: mysql-service-questions
            # PMA_PORT: 3306
            # MYSQL_USER: springuser 
            # MYSQL_PASSWORD: springpassword
            # MYSQL_ROOT_PASSWORD: example
            # MYSQL_DATABASE: question_service_db
        # links:
            # - mysql-service-questions
        # depends_on: 
            # - mysql-service-questions
        # ports:
        # #- HOST:CONTAINER
            # - 8081:80
            # - 8443:443

# Uncomment to enable volume creation
# volumes:
#   database_vol:
#     driver_opts:
#       type: none
#       device: /home/<path-to-destination>/data
#       o: bind

networks:
    local:
    outside:
        name: ecommerce_default
